### ISSUE TITLE
部分fa字体的图标无法显示或不能正常显示

### ISSUE THREAD

**Issue by b2cstory** [HCLonely/hexo-theme-webstack#19]
请问有解决的方法嘛？感激不尽！

**Comment by HCLonely** [comment]
自行添加相应的css链接即可
```yml
custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <link rel="stylesheet" type="text/css" href="custom.css">
```

**Comment by b2cstory** [comment]
> 自行添加相应的css链接即可
> 
> ```yaml
> custom:
>   head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
>     <link rel="stylesheet" type="text/css" href="custom.css">
> ```

谢谢回复，可是这个字体是项目里自带的，我看了一下已经添加了对应的css链接了呀。
<img width="710" alt="iShot2022-04-09 22 11 13" src="https://user-images.githubusercontent.com/103050465/162577913-a373eb85-6441-4196-9b5b-7668cb7f74ba.png">

**Comment by HCLonely** [comment]
项目里自带的是5.13免费版的，如果你是用了其他版本的图标就不能正常显示

**Comment by b2cstory** [comment]
> 项目里自带的是5.13免费版的，如果你是用了其他版本的图标就不能正常显示

谢谢，我想我找到问题所在了，原来是有 fas fab 和 far 三个 css 的，我一开始以为只有 fas 这一个，现在可以正常显示啦！

**Comment by yansheng836** [comment]
> 自行添加相应的css链接即可
> 
> ```yaml
> custom:
>   head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
>     <link rel="stylesheet" type="text/css" href="custom.css">
> ```

很奇怪，我尝试在css里面添加，但是好像没有生效

https://github.com/HCLonely/hexo-theme-webstack/blob/master/_config.example.yml#L117-L126

我感觉是这个Object有指定什么值……

https://github.com/HCLonely/hexo-theme-webstack/blob/master/layout/common/head.ejs#L10

**Comment by HCLonely** [comment]
> > 自行添加相应的css链接即可
> > ```yaml
> > custom:
> >   head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
> >     <link rel="stylesheet" type="text/css" href="custom.css">
> > ```
> 
> 很奇怪，我尝试在css里面添加，但是好像没有生效
> 
> [https://github.com/HCLonely/hexo-theme-webstack/blob/master/_config.example.yml#L117-L126](https://github.com/HCLonely/hexo-theme-webstack/blob/master/_config.example.yml?rgh-link-date=2022-09-12T07%3A08%3A45Z#L117-L126)
> 
> 我感觉是这个Object有指定什么值……
> 
> [https://github.com/HCLonely/hexo-theme-webstack/blob/master/layout/common/head.ejs#L10](https://github.com/HCLonely/hexo-theme-webstack/blob/master/layout/common/head.ejs?rgh-link-date=2022-09-12T07%3A08%3A45Z#L10)

你怎么添加的？

**Comment by yansheng836** [comment]
```
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  fontawesomea: /css/fonts/fontawesome/css/font-awesome.min.css
```
还是图标问题，我直接下载了新的，想把它也直接引入，但是没有生效。

**Comment by yansheng836** [comment]
```yml
custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <link rel="stylesheet" href="/css/fonts/fontawesome/css/font-awesome.min.css">
```

刚试了下，这个好像也引入不了。
直接在head.ejs 添加就可以
